<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="29007" started-at="2017-10-04T03:57:02Z" finished-at="2017-10-04T03:57:31Z">
    <groups>
      <group name="smoke">
        <method signature="SampleTest.someTest2(java.lang.Integer, java.lang.String)[pri:0, instance:com.selenium.Webdriver.dataproviderTests.SampleTest@3567135c]" name="someTest2" class="com.selenium.Webdriver.dataproviderTests.SampleTest"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Command line test" duration-ms="29007" started-at="2017-10-04T03:57:02Z" finished-at="2017-10-04T03:57:31Z">
      <class name="com.selenium.Webdriver.dataproviderTests.SampleTest">
        <test-method status="FAIL" signature="someTest2(java.lang.Integer, java.lang.String)[pri:0, instance:com.selenium.Webdriver.dataproviderTests.SampleTest@3567135c]" name="someTest2" duration-ms="0" started-at="2017-10-04T09:27:31Z" data-provider="mapAuth" finished-at="2017-10-04T09:27:31Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.selenium.Webdriver.dataproviderTests.SampleTest.someTest2(java.lang.Integer,java.lang.String) requires a @DataProvider named : mapAuth in class com.selenium.Webdriver.dataproviderTests.DataProvideClass]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.selenium.Webdriver.dataproviderTests.SampleTest.someTest2(java.lang.Integer,java.lang.String) requires a @DataProvider named : mapAuth in class com.selenium.Webdriver.dataproviderTests.DataProvideClass
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:265)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:414)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- someTest2 -->
      </class> <!-- com.selenium.Webdriver.dataproviderTests.SampleTest -->
      <class name="com.selenium.Webdriver.GetAllLinksTest">
        <test-method status="PASS" signature="gettest()[pri:0, instance:com.selenium.Webdriver.GetAllLinksTest@35fb3008]" name="gettest" duration-ms="28986" started-at="2017-10-04T09:27:02Z" finished-at="2017-10-04T09:27:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gettest -->
      </class> <!-- com.selenium.Webdriver.GetAllLinksTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
